### PR TITLE
Update TODO file

### PR DESCRIPTION
**Pull request by StykMartin**
Signed-off-by: Martin Styk <mastyk@redhat.com>

### CODE REVIEW

**Comment by jpopelka** [comment]
Looks like https://github.com/packit-service/packit/issues/398
I'm not sure what's the current state and whether it's already possible to do that (with [create-archive action](https://packit.dev/docs/actions/#creating-srpm) maybe?).
@dhodovsk @lachmanfrantisek may have more info

**Comment by StykMartin** [comment]
@jpopelka yeah .. it looks like packit-service/packit#398

**Pull request closed without merging**
